Repository kiwiproject/dropwizard-config-providers, pull requests merged in 2020-09, with the labels that each got.

#12 Use try-with-resources to ensure reader is closed
  src/main/java/org/kiwiproject/config/ExternalPropertyProvider.java
Labels: bug

#11 Add ResolvedBy to track how a property was set
  src/main/java/org/kiwiproject/config/ConfigProvider.java
  src/main/java/org/kiwiproject/config/ExternalPropertyProvider.java
  src/main/java/org/kiwiproject/config/NetworkIdentityProvider.java
  src/main/java/org/kiwiproject/config/ResolvedBy.java
  src/test/java/org/kiwiproject/config/ConfigProviderTest.java
  src/test/java/org/kiwiproject/config/NetworkIdentityProviderTest.java
Labels: enhancement

#16 Create model to hold all valid lookup "keys" for a property
  src/main/java/org/kiwiproject/config/FieldResolverStrategy.java
  src/main/java/org/kiwiproject/config/NetworkIdentityProvider.java
  src/main/java/org/kiwiproject/config/ServiceIdentityProvider.java
  src/test/java/org/kiwiproject/config/NetworkIdentityProviderTest.java
  src/test/java/org/kiwiproject/config/ServiceIdentityProviderTest.java
Labels: enhancement

#17 Add TlsPropertyProvider
  src/main/java/org/kiwiproject/config/ServiceIdentityProvider.java
  src/main/java/org/kiwiproject/config/TlsPropertyProvider.java
  src/test/java/org/kiwiproject/config/TlsPropertyProviderTest.java
  src/test/resources/TlsPropertyProvider/config.properties
Labels: new feature

#18 Prep for initial release
  README.md
  maven-central-deploy.sh
Labels: documentation

#36 Fix the order of resolution so that external comes before default
  src/main/java/org/kiwiproject/config/provider/FieldResolverStrategy.java
  src/main/java/org/kiwiproject/config/provider/ResolvedBy.java
  src/main/java/org/kiwiproject/config/provider/TlsConfigProvider.java
  src/main/java/org/kiwiproject/config/provider/util/SinglePropertyResolver.java
  src/test/java/org/kiwiproject/config/provider/ActiveMQConfigProviderTest.java
  src/test/java/org/kiwiproject/config/provider/NetworkIdentityConfigProviderTest.java
  src/test/java/org/kiwiproject/config/provider/ServiceIdentityConfigProviderTest.java
  src/test/java/org/kiwiproject/config/provider/TlsConfigProviderTest.java
  src/test/java/org/kiwiproject/config/provider/ZooKeeperConfigProviderTest.java
Labels: bug
